### ISSUE TITLE
Wrong namespace used for Inflector

### ISSUE THREAD

**Issue by pfrenssen** [api-platform/schema-generator#102]
When I install schema-generator through Composer and try to generate the data types I get the following fatal error:

```
$ ./vendor/bin/schema generate-types src/ app/config/schema.yml 
PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Util\Inflector' not found in /home/pieter/v/screeningapi/vendor/api-platform/schema-generator/src/TypesGenerator.php:651
Stack trace:
#0 /home/pieter/v/screeningapi/vendor/api-platform/schema-generator/src/TypesGenerator.php(222): ApiPlatform\SchemaGenerator\TypesGenerator->generateField(Array, Array, Object(EasyRdf_Resource), 'Thing', 'name', Object(EasyRdf_Resource))
#1 /home/pieter/v/screeningapi/vendor/api-platform/schema-generator/src/Command/GenerateTypesCommand.php(138): ApiPlatform\SchemaGenerator\TypesGenerator->generate(Array)
#2 /home/pieter/v/screeningapi/vendor/symfony/console/Command/Command.php(276): ApiPlatform\SchemaGenerator\Command\GenerateTypesCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/pieter/v/screeningapi/vendor/symfony/console/Application.php(933): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\ in /home/pieter/v/screeningapi/vendor/api-platform/schema-generator/src/TypesGenerator.php on line 651
```

The standalone Inflector package has renamed this namespace before their 1.0.0 release, see https://github.com/doctrine/inflector/commit/54b8333d2a5682afdc690060c1cf384ba9f47f08#diff-9e179a11e3e7c8687e189c2288f2b3bcR20

**Comment by dunglas** [comment]
Wow, it's super weird that our tests are green as we require `^1.0`.
Would you opening a PR?
